### ISSUE TITLE
Question about semicolon spacing

### ISSUE THREAD

**Issue by panmau** [G-Research/fsharp-formatting-conventions#35]
Does this styleguide recommend adding spaces before and after semicolons? I couldn't find any explicit mention of it but all examples do have a space before the semicolon:
```fsharp
let point = { X = 1.0 ; Y = 0.0 }
```

If that is the case that should probably be mentioned and the editorconfig updated as a space before the semicolons is per default set to off in Fantomas.
Thanks in advance for the clarification.

**Comment by Smaug123** [comment]
Hi - yes, that's correct. I thought it was specified somewhere; I'll see if I can make this clearer.

I'll also do a pass over the .editorconfig to make sure it's actually in alignment with what we use! I think this repo was created back when Fantomas was considerably less mature than it is now, and there's a chance we have not correctly used this repo as our source of truth.

**Comment by panmau** [comment]
Thanks a lot for the clarification and the fix of the editorconfig.
