### ISSUE TITLE
Long function signature

### ISSUE THREAD

**Issue by nojaf** [G-Research/fsharp-formatting-conventions#4]
I'm not entirely sure about this one but here goes:

To tackle https://github.com/fsprojects/fantomas/issues/495, if I remember correctly, we internally aligned on how the GR way of solving this bug would be.
I think the part of having the `=` on a separate line was proposed by you folks.
Could we add a section on how long functions should be formatted?

The thing I'm after here is to know what the rule is about indenting the rest of the function after the function name.

For example:
```fsharp
let someName
    (a : int)
    (b : int)
    : int
    =
    // start of function
    a + b
```

My question is about the spaces before `(a : int)`, are they one indentation length (4 spaces in this example), or do the align the start of `someName`?
If the indentation is 4 spaces they are one and the same.
Related Fantomas bug: https://github.com/fsprojects/fantomas/issues/883

**Comment by Smaug123** [comment]
I'd never really thought about it, but I think it's one indentation length (assuming that actually compiles).

**Comment by nojaf** [comment]
Yes, it compiles:
![image](https://user-images.githubusercontent.com/2621499/83905767-88ae9d80-a762-11ea-8261-5e3e11ff0832.png)

So I'm guessing the fix in Fantomas should be focussed on one indentation.

I opened the [question ](https://github.com/dotnet/docs/issues/18806)on how to format long signatures at the Microsoft style guide.
They might see things differently than how GR would do it.
So maybe it is a good idea to add this guide as well?
