### ISSUE TITLE
Fantomas configuration

### ISSUE THREAD

**Issue by nojaf** [G-Research/fsharp-formatting-conventions#6]
Would it be a good idea to have the Fantomas settings (in an .editorconfig) necessary to adhere to this guide?

**Comment by Smaug123** [comment]
I'd definitely be in favour of that. Were you volunteering? ;) if not, I can probably find a few minutes at some point.

**Comment by nojaf** [comment]
I can do an attempt and maybe you can complete it if I missed anything?

**Comment by Smaug123** [comment]
Sure, that would be great - thanks!
